from openpyxl import load_workbook
from werkzeug.security import generate_password_hash

from app.managers.admin_manager import AdminManager
from app.models import Student
from app.services.id_generators import next_teacher_id


SEMESTER_MAP = {
    '1': 'Spring',
    '2': 'Summer',
    '3': 'Fall',
    'Spring': 'Spring',
    'Summer': 'Summer',
    'Fall': 'Fall',
}


def clean_excel_value(value):
    """
    Convert Excel values safely:
    3.0 -> '3'
    2024.0 -> '2024'
    text -> stripped text
    None -> ''
    """
    if value is None:
        return ''

    if isinstance(value, float):
        if value.is_integer():
            return str(int(value))
        return str(value).strip()

    if isinstance(value, int):
        return str(value)

    return str(value).strip()


def import_students(db, file_path):
    wb = load_workbook(file_path)
    ws = wb.active

    manager = AdminManager(db)
    count = 0

    # Excel columns:
    # A = Student ID (ignored, auto-generated by backend)
    # B = Full Name
    # C = Email
    # D = Department
    # E = Semester Code
    # F = Year
    # G = Default Password
    # H = Notes (ignored)

    # Your uploaded file starts data from row 2
    for row in ws.iter_rows(min_row=2, values_only=True):
        if not row:
            continue

        name = clean_excel_value(row[1]) if len(row) > 1 else ''
        email = clean_excel_value(row[2]) if len(row) > 2 else ''
        department = clean_excel_value(row[3]).upper() if len(row) > 3 else ''
        semester_raw = clean_excel_value(row[4]) if len(row) > 4 else ''
        year = clean_excel_value(row[5]) if len(row) > 5 else ''
        raw_password = clean_excel_value(row[6]) if len(row) > 6 else ''

        # Skip fully empty rows
        if not any([name, email, department, semester_raw, year, raw_password]):
            continue

        # Required fields
        if not name or not email or not department or not semester_raw or not year:
            continue

        semester = SEMESTER_MAP.get(semester_raw.title(), SEMESTER_MAP.get(semester_raw))
        if not semester:
            continue

        # Skip duplicate email
        existing = db.execute(
            'SELECT id FROM users WHERE email=?',
            (email,)
        ).fetchone()
        if existing:
            continue

        student = Student(
            id=None,
            name=name,
            email=email,
            password_hash='',
            department=department,
            student_id='',
            admission_term=''
        )

        manager.create_student(
            student,
            raw_password=raw_password or None,
            year=year,
            semester=semester
        )

        count += 1

    db.commit()
    return count


def import_teachers(db, file_path):
    wb = load_workbook(file_path)
    ws = wb.active
    count = 0

    for row in ws.iter_rows(min_row=2, values_only=True):
        if not row:
            continue

        name = clean_excel_value(row[0]) if len(row) > 0 else ''
        email = clean_excel_value(row[1]) if len(row) > 1 else ''
        department = clean_excel_value(row[2]).upper() if len(row) > 2 else ''
        teacher_id = clean_excel_value(row[3]) if len(row) > 3 else ''

        if not name or not email or not department:
            continue

        existing = db.execute(
            'SELECT id FROM users WHERE email=?',
            (email,)
        ).fetchone()
        if existing:
            continue

        if not teacher_id:
            teacher_id = next_teacher_id(db, department)

        db.execute(
            'INSERT INTO users(role,name,email,password_hash,department) VALUES(?,?,?,?,?)',
            ('teacher', name, email, generate_password_hash('teacher123'), department)
        )
        user_id = db.execute(
            'SELECT id FROM users WHERE email=?',
            (email,)
        ).fetchone()['id']

        db.execute(
            'INSERT INTO teachers(user_id,teacher_id) VALUES(?,?)',
            (user_id, teacher_id)
        )
        count += 1

    db.commit()
    return count


def import_courses(db, file_path):
    wb = load_workbook(file_path)
    ws = wb.active
    count = 0

    for row in ws.iter_rows(min_row=2, values_only=True):
        if not row:
            continue

        course_code = clean_excel_value(row[0]) if len(row) > 0 else ''
        title = clean_excel_value(row[1]) if len(row) > 1 else ''
        credit = clean_excel_value(row[2]) if len(row) > 2 else ''

        if not course_code or not title or not credit:
            continue

        existing = db.execute(
            'SELECT id FROM courses WHERE course_code=?',
            (course_code,)
        ).fetchone()
        if existing:
            continue

        db.execute(
            'INSERT INTO courses(course_code,title,credit) VALUES(?,?,?)',
            (course_code, title, int(float(credit)))
        )
        count += 1

    db.commit()
    return count